// <auto-generated />
namespace CareerTech.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class update_company_profile : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(update_company_profile));
        
        string IMigrationMetadata.Id
        {
            get { return "202110171005541_update_company_profile"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
