using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace CareerTech.Utils
{
    public class LogConstants
    {
        public static string MODEL_INVALID = "Model state invalid";
        public static string ADD_RECRUITMENT_SUCCESS = "Add recruitment success";
        public static string CREATE_COMPANY_SUCCESS = "Create profile company success";
        public static string UPDATE_COMPANY_SUCCESS = "Update company profile success";
        public static string UPDATE_PARTNER_PROFILE_SUCCESS = "Update partner profile sucscess";
        public static string DELETE_RECRUITMENT_SUCCESS = "Delete recruitment sucscess";
        public static string UPDATE_RECRUITMENT_SUCCESS = "Update recruitment success";
        public static string DELETE_CANDIDATE_SUCCESS = "Delete candidate success";
        public static string UPDATE_CANDIDATE_SUCCESS = "Update candidate success";

        public static string LOG_USER_DASHBOARD = "User dashboard";
        public static string LOG_APPLY_RECRUITMENT = "Apply recruitment";
        public static string LOG_NULL_MAIN_PORTFOLIO = "Main port portfolio null";
        public static string LOG_APPLY_ALREADY = "Apply already";
        public static string LOG_SEARCH_RECRUITMENT = "Search recruitment";
        public static string LOG_USER_PROFILE = "User profile";
        public static string LOG_EDIT_USER_PROFILE = "Edit user profile";
        public static string LOG_PORTFOLIO_PAGE = "Portfolio page";
        public static string LOG_PORTFOLIO_NOT_FOUND = "Portfolio not found";
        public static string LOG_PORTFOLIO_NOT_PUBLIC = "Portfolio not public";
        public static string LOG_NULL_PROFILE_PORTFOLIO = "Profile portfolio is null";
        public static string LOG_DOWNLOAD_PORTFOLIO = "Download portfolio";
        public static string LOG_GET_IMAGE_URL = "Get image url";
        public static string LOG_PORTFOLIO_MANAGER = "Portfolio manager";
        public static string LOG_CREATE_PORTFOLIO = "Create portfolio";
        public static string LOG_DELETE_PORTFOLIO = "Delete portfolio";
        public static string LOG_DUPLICATE_NAME = "Name is already exist";
        public static string LOG_CHANGE_PUBLIC_STATUS = "Change public status portfolio";
        public static string LOG_PROFILE_PORTFOLIO = "Profile portfolio";
        public static string LOG_SKILL_MANAGER = "Skill manager";
        public static string LOG_ADD_SKILL = "Add skill";
        public static string LOG_EDIT_SKILL = "Edit skill";
        public static string LOG_SKILL_NOT_FOUND = "Skill not found";
        public static string LOG_DELETE_SKILL = "Delete skill";
        public static string LOG_EDUCATION_MANAGER = "Education manager";
        public static string LOG_ADD_EDUCATION = "Add education";
        public static string LOG_EDIT_EDUCATION = "Edit education";
        public static string LOG_EDUCATION_NOT_FOUND = "Education not found";
        public static string LOG_DELETE_EDUCATION = "Delete education";
        public static string LOG_EXPERIENCE_MANAGER = "Experience manager";
        public static string LOG_ADD_EXPERIENCE = "Add experience";
        public static string LOG_EDIT_EXPERIENCE = "Edit experience";
        public static string LOG_EXPERIENCE_NOT_FOUND = "Experience not found";
        public static string LOG_DELETE_EXPERIENCE = "Delete experience";
        public static string LOG_PRODUCT_MANAGER = "Product manager";
        public static string LOG_ADD_PRODUCT = "Add product";
        public static string LOG_EDIT_PRODUCT = "Edit product";
        public static string LOG_PRODUCT_NOT_FOUND = "Product not found";
        public static string LOG_DELETE_PRODUCT = "Delete product";
        public static string LOG_CREATE_PROFILE_PORTFOLIO = "Create profile portfolio";
        public static string LOG_EDIT_PROFILE_PORTFOLIO = "Edit profile portfolio";
        public static string LOG_FAIL = "Fail";
        public static string LOG_SUCCESS = "Success";
        public static string LOG_GET_EDUCATION = "Get education";
        public static string LOG_GET_LIST_EDUCATION = "Get list education";
        public static string LOG_GET_EXPERIENCE = "Get experience";
        public static string LOG_GET_LIST_EXPERIENCE = "Get list experience";
        public static string LOG_GET_PORTFOLIO = "Get portfolio";
        public static string LOG_GET_LIST_PORTFOLIO = "Get list portfolio";
        public static string LOG_GET_PRODUCT = "Get product";
        public static string LOG_GET_LIST_PRODUCT = "Get list product";
        public static string LOG_GET_PROFILE_PORTFOLIO = "Get profile";
        public static string LOG_GET_SKILL = "Get skill";
        public static string LOG_GET_LIST_SKILL = "Get list skill";
        public static string LOG_SET_MAIN_PORTFOLIO = "Set main portfolio";
        public static string LOG_GET_LIST_SEARCH_RECRUITMENT = "Get list search recruitment";
        public static string LOG_GET_LIST_DASHBOARD_RECRUITMENT = "Get list dashboard recruitment";
        public static string LOG_COUNT_CANDIDATE = "Count candidate";
        public static string LOG_GET_COMPANY_STATUS = "Get company status";
        public static string LOG_GET_CANDIDATE = "Get candidate";
        public static string LOG_ADD_CANDIDATE = "Add candidate";

        public static string LOG_ADD_SUBSCRIPTION = "Add new subscription ";
        public static string LOG_ADD_CONTENT = "Add new content ";
        public static string LOG_ADD_ABOUT = "Add new about ";
        public static string LOG_ADD_SOLUTION = "Add new solution ";
        public static string LOG_ADD_ORDER = "Add new order ";
        public static string LOG_ADD_PAYMENT = "Add new payment ";
        public static string LOG_EDIT_SUBSCRIPTION = "update subscription ";
        public static string LOG_EDIT_CONTENT = "update content ";
        public static string LOG_EDIT_ABOUT = "update about ";
        public static string LOG_EDIT_SOLUTION = "update solution ";
        public static string LOG_EDIT_ORDER = "update order ";
        public static string LOG_GET_SUBSCIPTION_BYID = "Subscription: ";
        public static string LOG_GET_ABOUT_BYID = "GET About by id: ";
        public static string LOG_GET_CONTENT_BYID = "GET Content  by id: ";
        public static string LOG_GET_SOLUTION_BYID = "GET Solution  by id: ";
        public static string LOG_GET_PARTNER_BYID = "GET Partner by id: ";
        public static string LOG_GET_ORDER_BYID = "GET order by id: ";
        public static string LOG_GET_ORDER_DETAIL_BYUSERID = "GET list order detail by userid: ";
        public static string LOG_GET_LIST_ORDER_DETAIL = "GET list order detail: ";
        public static string LOG_GET_PARTNERWITHCOMPANY_BYID = "GET PartnerWithCompanyProfile by id: ";
        public static string LOG_MAIN_EXISTED = "Main existed";
        public static string LOG_SET_MAIN = "Main doesnt exist";
        public static string LOG_GET_USER = "Get List User ";
        public static string LOG_GET_PARTNER = "Get List Partner ";
        public static string LOG_GET_PARTNERWITHCOMPANY = "Get List Partner With Company Profile ";
        public static string LOG_GET_LIST_ABOUT = "Get list about";
        public static string LOG_GET_LIST_CONTENT = "Get list content";
        public static string LOG_GET_LIST_SOLUTION = "Get list solution";
        public static string LOG_GET_LIST_SUBSCRIPTION = "Get list subscription";
        public static string LOG_MAIN_ABOUT = "GET MAIN ABOUT:";
        public static string LOG_MAIN_CONTENT = "GET MAIN CONTENT:";
        public static string LOG_DELETE_CONTENT = "GET MAIN CONTENT:";
        public static string LOG_DELETE_ABOUT = "GET MAIN CONTENT:";
        public static string LOG_DELETE_USER = "GET MAIN CONTENT:";
        public static string LOG_DELETE_SUBSCRIPTION = "GET MAIN CONTENT:";
        public static string LOG_DELETE_SOLUTION = "GET MAIN CONTENT:";
        public static string LOG_GET_ABOUT = "Get first About: ";
        public static string LOG_GET_CONTENT = "Get first content: ";
        public static string LOG_GET_LIST_PENDING_ORDER = "Get list pending order";
        public static string LOG_NUMBER_OF_USER = "Number of user: ";
        public static string LOG_NUMBER_OF_PARTNER = "Number of partner: ";
        public static string LOG_ADD_SERVICE_TIME = "Add service time: ";
        public static string LOG_GET_SERVICE_TIME = "GET service time: ";
        public static string LOG_COMPARE_ENDDATE_NOW = "See user service remaining time: ";
        public static string APPROVE_PARTNER = "Approve Partner";
        public static string REJECT_PARTNER = "REJECT Partner";
        public static string DOWNLOAD_USER_INFO = "Download All User Info";
        public static string PARTNER_TIME_EXISED = "Partner Time Existed";
        public static string PARTNER_NOT_TIME_EXISED = "Partner Time Doesnt Existed";
        public static string GET_ALL_PARTNER_WITH_SERVICE = "GET ALL PARTNERS_WITH SERVICE";
        public static string LOG_NULL_VALUE = "Null value";

    }
}